- name: Desplegar aplicación como contenedor con secretos
  hosts: target1
  become: true

  tasks:
    - name: Desplegar contenedor quotes con credenciales inyectadas como env vars
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        restart_policy: unless-stopped
        pull: true
        ports:
          - "{{ app_port }}:8000"
        env:
          POSTGRES_HOST: "{{ postgres_host }}"
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "{{ postgres_db }}"
      no_log: true # Evitar registar la salida de la tasks

    - name: Mostrar configuración (sin secretos)
      debug:
        msg: |
          App: {{ app_name }}
          Puerto: {{ app_port }}
          Postgres Host: {{ postgres_host }}
          Postgres Password: ******** (oculto por seguridad)