[madrid]
target1 ansible_host=target1
target2 ansible_host=target2

[barcelona]
target3 ansible_host=target3 

[servers:children]
madrid
barcelona

[all:vars]
# Conectamos a localhost y cada host usa un puerto distinto redirigido al contenedor
ansible_user=ansible