http:
  routers:
    __ALUMNO_ID__:
      rule: "Host(`__ALUMNO_ID__.__DOMINIO__`)"
      entryPoints:
        - websecure
      service: __ALUMNO_ID__-svc
      tls:
        certResolver: myresolver

  services:
    __ALUMNO_ID__-svc:
      loadBalancer:
        servers:
          - url: "http://__ALUMNO_ID__-control:8443"
